---
title: "03.1 Factores: Canal endémico"
author: "CDC - GT Investigación"
date: '`r Sys.time()`'
output: 
  html_document:
    #pdf_document:
    toc: TRUE
    number_sections: true
    toc_float: TRUE
    code_folding: hide
    df_print: kable
    highlight: tango
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE,message = FALSE,fig.align = "center")
options(knitr.kable.NA = '.',digits = 2)
```

# paquetes

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(magrittr)
library(cdcper)
theme_set(theme_bw())
```

# importar bases

## vigilancia de EDA: 2012-2018

```{r}
# se requiere al menos 7 años de información de una determinada enfermedad 
# Estructura de base: 
# N° de casos y poblacion por area (depa,prov,dist), Tiempo (semana o mes)

#Ejemplo: Canal Endemico_EDA por distrito y por semana . 

# Bases EDA y pob por distrito, año y SE  2012-2018
edapr_dis <- read_rds("data-raw/eda_12_18.rds") #%>% mutate(semana=as.factor(semana))
pob_long <- read_rds("data-raw/pob_ubigeo12_18.rds") %>% 
  rename(pob=value) %>% 
  filter(ubigeo!="Total general")
```

## vigilancia de EDA y SGB: 2019

```{r}
# ABRIMOS BASE----
# sgb19_dis <- read_rds("data-raw/sgb19_dis.rds")
eda19_dis <- read_rds("data-raw/eda19_dis.rds")
ubigeo <- read_excel("data-raw/nombres_ubigeo.xlsx") %>% 
  mutate(ubigeo=as.factor(ubigeo)) %>% 
  clean_names()
```

# metodo: canal endémico

```{r}
edapr_dis %>% 
  complete(ubigeo,
           semana=full_seq(semana,1),
           year=full_seq(year,1),fill = list(eda=0)) %>% 
  #filter(ubigeo=="010102") %>% avallecam::print_inf()
  left_join(pob_long) %>% 
  filter(ubigeo=="010102",semana==5) %>% 
  #Paso 2: Cálculo de tasas y suma 1 (facilitar transformación en 0 casos)
  mutate(tasa=eda/pob*100000+1,
         #Paso 3: Transformación logarítmica de las tasas
         log_tasa=log(tasa)) %>% 
  avallecam::print_inf()
```

```{r}
# Metodologia: calculando el canal endemico 

#Paso 1:  N° de casos  por semana,  7 años
edapr_dis %>% 
  complete(ubigeo,
           semana=full_seq(semana,1),
           year=full_seq(year,1),fill = list(eda=0)) %>% 
  #Paso 1.2: unir con el tamaño poblacional por ubigeo-anho
  left_join(pob_long) %>% 
  #Paso 1.3: retirar ubigeos sin poblacion para ningun anho
  #naniar::miss_var_summary()
  #filter(is.na(pob)) %>% count(ubigeo,year) %>% count(n)
  filter(!is.na(pob)) %>% 
  #Paso 2: Cálculo de tasas y suma 1 (facilitar transformación en 0 casos)
  mutate(tasa=eda/pob*100000+1,
         #Paso 3: Transformación logarítmica de las tasas
         log_tasa=log(tasa)) %>%
  # Paso 4: Cálculo de medias, 1*DE y delimitacion del 68.26% de valores del log_tasas
  group_by(ubigeo, semana) %>%
  summarise(media_l=mean(log_tasa), sd_l=sd(log_tasa)) %>%
  mutate(lo_95_l=media_l-(1*sd_l), hi_95_l=media_l+(1*sd_l)) %>%
  ungroup() %>%
  # Paso 5: Transformación a unidades originales (de log_tasas a tasas), menos 1 (agregado arriba)
  mutate(media_t= exp(media_l)-1, #sd_t= exp(sd_l)-1,
         lo_95_t=exp(lo_95_l)-1, hi_95_t=exp(hi_95_l)-1) %>%
  # Paso 6: Transformación a de tasas a casos (esperados)
  left_join(pob_long %>%
              group_by(ubigeo) %>%
              summarise(media_pob=mean(pob))%>%
              ungroup()) %>%
  mutate(media=media_t*media_pob/100000,
         lo_95=lo_95_t*media_pob/100000,
         hi_95=hi_95_t*media_pob/100000) %>%
  # seleccionado solo las variables a usar
  select(ubigeo, semana, media, lo_95, hi_95) %>%
  #mutate(key=name)%>%
  mutate(ubigeo=as.factor(ubigeo)) %>% 
  #mostrar head
  slice(1:25)
```

### conf int

```{r,eval=TRUE}
# Metodologia: calculando el canal endemico 
#Paso 1:  N° de casos  por semana,  7 años
edapr_dis %>% 
  complete(ubigeo,
           semana=full_seq(semana,1),
           year=full_seq(year,1),
           fill = list(eda=0)
           ) %>% 
  #Paso 1.2: unir con el tamaño poblacional por ubigeo-anho
  left_join(pob_long) %>% 
  #Paso 1.3: retirar ubigeos sin poblacion para ningun anho
  #naniar::miss_var_summary()
  #filter(is.na(pob)) %>% count(ubigeo,year) %>% count(n)
  filter(!is.na(pob)) %>% 
  #Paso 2: Cálculo de tasas y suma 1 (facilitar transformación en 0 casos)
  mutate(tasa=eda/pob*100000+1,
         #Paso 3: Transformación logarítmica de las tasas
         log_tasa=log(tasa)) %>%
  #skimr::skim(log_tasa)
  
  group_by(ubigeo, semana) %>%
  
  # Paso 4: Cálculo de media e IC95% de log_tasas
  nest() %>% 
  ungroup() %>% 
  slice(1:54) %>% #for demostration
  #unnest(cols = c(data))
  
  # #issue tagged -> non-vairability stops t.test
  # count(log_tasa,sort = T) %>%
  # ungroup() %>% filter(n==7) %>% 
  # count(ubigeo,sort = T)
  # count(log_tasa)
  # filter(is.na(log_tasa)) %>% 
  # count(ubigeo) 
  #retirar semana con puro cero o NA
  
  # #PLAN 01
  # mutate(sum_tasa=map_dbl(.x = data,.f = ~sum(.$log_tasa),na.rm=TRUE)) %>% #arrange(sum_tasa)
  # filter(sum_tasa>0) %>%
  # mutate(t_test=map(.x = data,.f = ~t.test(.$log_tasa))) %>%
  # mutate(tidied=map(t_test,broom::tidy)) %>% 
  # unnest(cols = c(tidied))

  #PLAN 02
  mutate(t_test=map(.x = data,.f = ~lm(log_tasa ~ 1,data=.x))) %>% 
  mutate(tidied=map(t_test,broom::tidy),
         tidy_ci=map(t_test,broom::confint_tidy)) %>% 
  unnest(cols = c(tidied,tidy_ci)) %>% 
  rename(media_l=estimate,
         lo_95_l=conf.low,
         hi_95_l=conf.high) %>% 
  
  # Paso 5: Transformación a unidades originales (de log_tasas a tasas), menos 1 (agregado arriba)
  mutate(media_t= exp(media_l)-1, #sd_t= exp(sd_l)-1,
         lo_95_t=exp(lo_95_l)-1, hi_95_t=exp(hi_95_l)-1) %>%
  # Paso 6: Transformación a de tasas a casos (esperados)
  left_join(pob_long %>%
              group_by(ubigeo) %>%
              summarise(media_pob=mean(pob))%>%
              ungroup()) %>%
  mutate(media=media_t*media_pob/100000,
         lo_95=lo_95_t*media_pob/100000,
         hi_95=hi_95_t*media_pob/100000) %>%
  # seleccionado solo las variables a usar
  select(ubigeo, semana, media, lo_95, hi_95) %>%
  #mutate(key=name)%>%
  mutate(ubigeo=as.factor(ubigeo)) %>% 
  #mostrar head
  slice(1:25)
```

# aplicación

## canal EDA por ubigeo

```{r}
edas_2019 <- eda19_dis %>% 
  #arreglar nombre de columna
  rename(value=eda) %>% 
  mutate(key="eda")
```

### método: 1*SD

```{r}
# crear datos del canal con información de años previos
cdc_endemic_channel_mutate(disease = edapr_dis,
                           population = pob_long,
                           name = "eda",
                           method = "gmean_1sd") %>% 
  # unir con anho a vigilar
  cdc_endemic_channel_join(disease_now = edas_2019) %>% 
  #formato: reordenar ubigeos descendentemente 
  #         segun la suma total de casos en lo que va del anho
  mutate(ubigeo=fct_reorder(ubigeo,value,sum),
         ubigeo=fct_rev(ubigeo)) %>% 
  #formato: filtrar top 10
  filter(as.numeric(ubigeo)<10) %>% 
  #generar grafico
  cdc_endemic_channel_ggplot() +
  #dividir grafico por ubigeos
  facet_wrap(~dpto+dist) +
  #retirar semana inicio y final por subestimacion
  xlim(2,52) +
  labs(title = "EDA a nivel distrital. Perú, 2019.",
       subtitle = "Método: Media Geométrica +/- 1 Desviación Estándar")
```

```{r}
ggsave("figure/0201-echannel-02-1sd.png",height=4,width=5,dpi = "retina")
```

### método: 2*SD

```{r}
# crear datos del canal con información de años previos
cdc_endemic_channel_mutate(disease = edapr_dis,
                           population = pob_long,
                           name = "eda",
                           method = "gmean_2sd") %>% 
  # unir con anho a vigilar
  cdc_endemic_channel_join(disease_now = edas_2019) %>% 
  #formato: reordenar ubigeos descendentemente 
  #         segun la suma total de casos en lo que va del anho
  mutate(ubigeo=fct_reorder(ubigeo,value,sum),
         ubigeo=fct_rev(ubigeo)) %>% 
  #formato: filtrar top 10
  filter(as.numeric(ubigeo)<10) %>% 
  #generar grafico
  cdc_endemic_channel_ggplot() +
  #dividir grafico por ubigeos
  facet_wrap(~dpto+dist) +
  #retirar semana inicio y final por subestimacion
  xlim(2,52) +
  labs(title = "EDA a nivel distrital. Perú, 2019.",
       subtitle = "Método: Media Geométrica +/- 2 Desviación Estándar")
```

```{r}
ggsave("figure/0201-echannel-03-2sd.png",height=4,width=5,dpi = "retina")
```

### método: 95% CI

```{r,eval=FALSE}
# crear datos del canal con información de años previos
cdc_endemic_channel_mutate(disease = edapr_dis,
                           population = pob_long,
                           name = "eda",
                           method = "gmean_ci") %>% 
  # unir con anho a vigilar
  cdc_endemic_channel_join(disease_now = edas_2019) %>% 
  #formato: reordenar ubigeos descendentemente 
  #         segun la suma total de casos en lo que va del anho
  mutate(ubigeo=fct_reorder(ubigeo,value,sum),
         ubigeo=fct_rev(ubigeo)) %>% 
  #formato: filtrar top 10
  filter(as.numeric(ubigeo)<10) %>% 
  #generar grafico
  cdc_endemic_channel_ggplot() +
  #dividir grafico por ubigeos
  facet_wrap(~dpto+dist) +
  #retirar semana inicio y final por subestimacion
  xlim(2,52) +
  labs(title = "EDA a nivel distrital. Perú, 2019.",
       subtitle = "Método: Media Geométrica +/- IC al 95%")
```

```{r,eval=FALSE}
ggsave("figure/0201-echannel-04-xic.png",height=4,width=5,dpi = "retina")
```

## canal EDA nacional

```{r}
cdc_endemic_channel_mutate(disease = edapr_dis,
                           population = pob_long,
                           name = "eda",
                           method = "gmean_1sd") %>% 
  # unir con anho a vigilar
  cdc_endemic_channel_join(disease_now = edas_2019) %>% 
  group_by(semana) %>% 
  summarise_at(.vars = vars(media:hi_95,value),.funs = sum,na.rm=TRUE) %>% 
  #generar grafico
  cdc_endemic_channel_ggplot() +
  #retirar semana inicio y final por subestimacion
  xlim(2,52) +
  labs(title = "EDA a nivel nacional. Perú, 2019.",
       subtitle = "Método: Media Geométrica +/- 1 Desviación Estándar")
```

```{r}
ggsave("figure/0201-echannel-01.png",height=4,width=5,dpi = "retina")
```

```{r}

```

<!-- ## canal EDA + casos SGB -->

<!-- ```{r} -->
<!-- # 2. Uniendo base----   -->
<!-- serie_eda_sgb<-full_join(eda19_dis, sgb19_dis) %>%  -->
<!--   mutate(sgb = replace_na(sgb, 0)) -->

<!-- # generando una base tipo LONG para el grafico comparado  -->
<!-- serie_eda_sgb_long <- serie_eda_sgb %>%  -->
<!--   pivot_longer(cols = c(eda,sgb),names_to = "key", values_to = "value") %>%  -->
<!--   mutate(ubigeo=as.factor(ubigeo)) -->

<!-- serie <- cdc_endemic_channel_mutate(disease = edapr_dis, -->
<!--                            population = pob_long, -->
<!--                            name = "eda") %>%  -->
<!--   full_join(serie_eda_sgb_long) %>%  -->
<!--   left_join(ubigeo %>% select(ubigeo,dist,prov,dpto))%>% -->
<!--   arrange(ubigeo,semana,key) %>%  -->
<!--   distinct() -->

<!-- ``` -->


<!-- ### ubigeos de interés -->

<!-- ```{r} -->
<!-- # distritos lambayeque -->
<!-- serie_lista3 <- serie %>%  -->
<!--   filter(dpto %in% c("LAMBAYEQUE"), -->
<!--          key=="sgb" & !is.na(value)) %>%  -->
<!--   distinct() %>% -->
<!--   group_by(ubigeo,dist, dpto) %>%  -->
<!--   summarise(sgb_sum=sum(value,na.rm = T)) %>%  -->
<!--   ungroup() %>%  -->
<!--   arrange(desc(sgb_sum)) %>%  -->
<!--   filter(sgb_sum>3) %>%  -->
<!--   arrange(desc(sgb_sum)) %>%  -->
<!--   pull(ubigeo) -->
<!-- ``` -->

<!-- ### canal -->

<!-- ```{r,echo=FALSE} -->
<!-- cdc_endemic_channel_exposure <- function(data) { -->

<!--   serie <- data -->

<!--   #generar los nombres de los distritos y depa para el titulo del grafico  -->
<!--   ubigeo_name <- serie %>%  -->
<!--     select(ubigeo) %>%  -->
<!--     distinct() %>% pull() -->

<!--   plot_name <- serie %>%    -->
<!--     select(dist,dpto) %>%  -->
<!--     distinct() %>% as.character() %>% paste(collapse = ", ") -->

<!--   #generando grafico del canal -->
<!--   distrito_plot <- serie %>%  -->
<!--     mutate(new= if_else(key=="eda", -->
<!--                         max(c(value,hi_95),na.rm = T), NA_real_), ) %>%  -->
<!--     ggplot(aes(x = semana, y = value, fill=key )) + -->
<!--     geom_area(aes(x=semana, y=new), fill = "#981000", alpha=0.6, stat="identity")+ -->
<!--     geom_area(aes(x=semana, y=hi_95), fill = "#fee76a", stat="identity")+ -->
<!--     geom_area(aes(x=semana, y=media), fill = "#3e9e39",  stat="identity")+ -->
<!--     geom_area(aes(x=semana, y=lo_95), fill = "white", stat="identity") + -->
<!--     #geom_col()+ -->
<!--     geom_line(size = 0.8) +  -->
<!--     facet_grid(key~.,scales ="free_y") +  -->
<!--     #facet_grid_sc(key~.,scales = list(y = scales_y)) +  -->
<!--     geom_vline(aes(xintercept=37),color="black", linetype="dashed", size=1)+  -->
<!--     geom_vline(aes(xintercept=44),color="black", linetype="dashed", size=1) + -->
<!--     scale_x_continuous(breaks =  seq(1, 52, 4)) + -->
<!--     #scale_y_continuous(breaks =  seq(0, max(value), 1)) + -->
<!--     theme(axis.text.x = element_text(size = rel(1.5)),  -->
<!--           axis.text.y = element_text(size = rel(1.5)), -->
<!--           axis.title = element_text(size = rel(1.5))) + -->
<!--     theme( strip.text.y = element_text(size = rel(1.5)),  -->
<!--            panel.grid = element_blank()) + -->
<!--     xlab("semanas") + ylab("N° de casos") + -->
<!--     labs(title = paste0("Distrito de ",plot_name)) -->

<!--   # ggsave(paste0("figure/fig11-canal_endemico_2019-",ubigeo_name,".png"), -->
<!--   #        height = 6,width = 6) -->

<!--   return(distrito_plot) -->

<!-- } -->

<!-- ``` -->

<!-- ```{r} -->
<!-- exposure <- serie %>%  -->
<!--   filter(ubigeo %in% serie_lista3) %>%  -->
<!--   mutate(ubigeo_x=ubigeo) %>%   -->
<!--   group_by(ubigeo_x) %>%  -->
<!--   nest() %>%  -->
<!--   mutate(plot_canal=map(data,cdc_endemic_channel_exposure)) %>%  -->
<!--   ungroup() -->

<!-- exposure %>% slice(2) %>% pull(plot_canal) -->

<!-- ``` -->

