---
title: "01. Detección: Series de tiempo"
author: "CDC - GT Investigación"
date: '`r Sys.time()`'
output: 
  #pdf_document:
  html_document:
    toc: TRUE
    number_sections: true
    toc_float: TRUE
    code_folding: hide
    #df_print: kable
    highlight: tango
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE,message = FALSE,fig.align = "center")
options(knitr.kable.NA = '.',digits = 2)
```

# paquetes

```{r}
# libraries ---------------------------------------------------------------

library(tidyverse)
library(forecast)
library(readxl)
library(lubridate)
library(sweep) #https://business-science.github.io/sweep/
library(magrittr)
library(janitor)
library(avallecam)
library(zoo)
library(tidyquant)

theme_set(theme_bw())

```

# importar data

```{r}
# import data -------------------------------------------------------------

cases_surveillance <- read_csv("data-raw/base estimaciones.csv") %>% 
  clean_names() %>% 
  rename(month=mes) %>% 
  select(year, month, departamento, total)

cases_surveillance %>% slice(1:15)
```

## dividir base

```{r}
# department level input ---------------------------------------------------

cases_surveillance_years <- cases_surveillance %>% 
  filter(is_in(year,2015:2018))

cases_observed_years <- cases_surveillance %>% 
  filter(year==2019)

```

# estimación nivel país

```{r}
# country level summary ---------------------------------------------------

cases_surveillance_years_country <- cases_surveillance_years %>% 
  group_by(year, month) %>% 
  summarise(total_country=sum(total, na.rm = T)) %>% 
  ungroup() %>% 
  arrange(year) 

cases_observed_country <- cases_observed_years %>% 
  group_by(year, month) %>% 
  summarise(total_country=sum(total, na.rm = T)) %>% 
  ungroup() %>% 
  arrange(year) 

cases_observed_country

```

## forecast / pronóstico

```{r}
# country level forecast ---------------------------------------------------

cases_forecast_country <- cases_surveillance_years_country %>% 
  ts(start=c(2015, 1), end=c(2018, 12), frequency=12) %>% 
  stlf(y = .[,3],h = 12)

cases_forecast_country %>% 
  sw_sweep() %>% 
  filter(!is.na(lo.80))
```

## gráfico

```{r}
# country expected ggplot -----------------------------------------------------

cases_forecast_country %>% 
  sw_sweep() %>%
  ggplot(aes(x = index, y = value, color = key)) +
  geom_ribbon(aes(ymin = lo.95, ymax = hi.95), 
              fill = "#D5DBFF", linetype = 0) +
  geom_ribbon(aes(ymin = lo.80, ymax = hi.80, fill = key), 
              fill = "#596DD5", linetype = 0, alpha = 0.8) +
  geom_line(size = 0.5) +
  geom_point(size = 0.6) +
  #ylim(0,600) +
  scale_x_yearmon(n = 12, format = "%b%Y") +
  scale_color_tq() +
  scale_fill_tq() +
  guides(color=guide_legend(override.aes=list(fill=NA))) + 
  labs(title = "Casos de SGB",
       caption = ,
       x = "", y = "N° casos",
       subtitle = "Proyección mediante decomposición STL") +
  theme_tq() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
ggsave("figure/0401-forecast-01-esp.png",height=4,width=5,dpi = "retina")
```


```{r,echo=FALSE}

gg_forecast <- function(data) {
  data %>%
    ggplot(aes(x = index, y = value, color = key)) +
    geom_ribbon(aes(ymin = lo.95, ymax = hi.95), 
                fill = "#D5DBFF", linetype = 0) +
    geom_ribbon(aes(ymin = lo.80, ymax = hi.80, fill = key), 
                fill = "#596DD5", linetype = 0, alpha = 0.8) +
    geom_line(size = 0.5) +
    geom_point(size = 0.5) +
    #ylim(0,600) +
    scale_x_yearmon(n = 12, format = "%b%Y") +
    #scale_x_yearmon(n = 12, format = "%Y / %m") +
    scale_color_tq() +
    scale_fill_tq() +
    guides(color=guide_legend(override.aes=list(fill=NA))) + 
    labs(title = "Casos de SGB",
         caption = ,
         x = "", y = "N° casos",
         subtitle = "Proyección mediante decomposición STL") +
    theme_tq() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
}

```

## gráfico + observado

```{r}
# country expected + observed ggplot --------------------------------------

cases_forecast_country_observed <- cases_forecast_country %>% 
  sw_sweep() %>% 
  mutate(year=as.POSIXlt(index) %>% year(),
         month=as.POSIXlt(index) %>% month()) %>% 
  select(-index) %>% 
  union_all(
    cases_observed_country %>% 
      mutate(key="observed") %>% 
      rename(value=total_country)
  ) %>% 
  mutate(
    index=str_c(year,"-",month),
    index=as.yearmon(index),
  ) 

#cases_forecast_country_observed %>% print_inf()

cases_forecast_country_observed %>% 
  gg_forecast() +
  ylim(0,600)
```


```{r}
ggsave("figure/0401-forecast-02-obs.png",height=4,width=5,dpi = "retina")
```


# estimación nivel departamento

```{r}
# department level forecast ------------------------------------------------

cases_forecast_bydepartment <- cases_surveillance_years %>% 
  group_by(departamento) %>% 
  nest() %>% 
  mutate(proyeccion=map(.x = data,
                        .f = ts,
                        start=c(2015, 1), #start observation
                        end=c(2018, 12), #end observation
                        frequency=12 #by each month
                        )) %>% 
  mutate(proyeccion_ic=map(.x = proyeccion,
                           .f = ~stlf(.[,3],h = 12))) %>% 
  mutate(proyeccion_tidy=map(proyeccion_ic,sw_sweep))

#cases_forecast_bydepartment
```

## agregar observados

```{r}
# department level forecast + observed -------------------------------------

cases_forecast_bydepartment_tidy <- cases_forecast_bydepartment %>% 
  select(departamento,proyeccion_tidy) %>% 
  unnest(cols = c(proyeccion_tidy)) %>% 
  ungroup() %>% 
  mutate(year=as.POSIXlt(index) %>% year(),
         month=as.POSIXlt(index) %>% month()) %>% 
  select(-index) %>% 
  union_all(
    cases_observed_years %>% 
      mutate(key="observed") %>% 
      rename(value=total)
  ) %>% 
  mutate(
    index=str_c(year,"-",month),
    index=as.yearmon(index)
  ) 

cases_forecast_bydepartment_tidy %>% 
  filter(departamento=="Lima") %>% 
  filter(year==2019)
```

## gráfico + observados

```{r,fig.height=9,fig.width=9}
# department expected + observed ggplot --------------------------------------------------

cases_forecast_bydepartment_tidy %>% 
  mutate(departamento=fct_reorder(departamento,value,max),
         departamento=fct_rev(departamento)) %>% 
  filter(as.numeric(departamento)<=9) %>% 
  gg_forecast() +
  facet_wrap(~departamento,scales = "free") #+
  #ylim(-15,225)

```


```{r}
ggsave("figure/0401-forecast-03-str.png",height=9,width=9,dpi = "retina")
```


```{r,eval=FALSE,echo=FALSE}
# department anual forecast ------------------------------------------------

cases_forecast_bydepartment_tidy %>% 
  arrange(departamento, month) %>% 
  filter(key=="forecast") %>% 
  group_by(departamento) %>% 
  summarise_at(.vars = vars(value:hi.95),.funs = sum) %>% 
  ungroup() %>% 
  print_inf()
```

