---
title: "05. Distribución: Regresión Espacial"
author: "CDC - GT Investigación"
date: '`r Sys.time()`'
output: 
  #pdf_document:
  html_document:
    toc: TRUE
    number_sections: true
    toc_float: TRUE
    code_folding: hide
    #df_print: kable
    highlight: tango
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE,message = FALSE,fig.align = "center")
options(knitr.kable.NA = '.',digits = 2)
```

## R Markdown

```{r}
# GAM MODEL --------------------------------------------------------------------
library(tidyverse)
library(sp)        # classes and methods for spatial data
# library(sf)        # simple features
library(spatstat)  # spatial point pattern analysis
library(maptools)  # reading and handling spatial objects
library(viridis)   # nice palette
library(fields)    # image.plot

preston_crime <- read_rds("data-raw/pcrime-spatstat.rds.gz.rds")
humberside <- preston_crime
levels(humberside$marks) <- c("control","case")

library(mgcv)
humber_df <- as.data.frame(humberside)
humber_df$cases <- 1 * (humber_df$marks == "case")

```


```{r}
library(broom)

gam_humber <- gam(cases ~ s(x, y, k = 100), 
                  data = humber_df, 
                  family = poisson(link = log))
                  # family = binomial(link = logit))
# plot(humberside$window)

# vis.gam(gam_humber, 
#         view=c("x","y"),
#         plot.type="contour",
#         color="heat", 
#         type = "link",
#         add = TRUE)

# plot(humberside$window, add = TRUE)
# points(controls, pch = "o", col = 4)
# points(cases, pch = "+", col = 2)

# gam.check(gam_humber)
```

```{r}
library(mgcViz)

gam_humber %>% summary() #rsquared + deviance explained
gam_humber %>% broom::tidy()
gam_humber %>% broom::tidy(parametric=TRUE)
gam_humber %>% broom::glance()
gam_humber %>% broom::augment()
gam_humber %>% broom::augment(type.predict="link")
gam_humber %>% broom::augment(type.predict="response")
gam_humber %>% broom::augment(type.predict="term")
gam_humber %>% plot()
gam_humber %>% vis.gam()
gam_humber %>% getViz() %>% sm(.,1) %>% plot()  

gam_humber_viz <- getViz(gam_humber)

gam_humber_viz_raster <- 
  plot(sm(gam_humber_viz, 1)) + 
  l_fitRaster() +
  l_fitContour()

gam_humber_viz_raster + coord_fixed()

gam_humber_viz_raster$data$fit %>% 
  as_tibble() %>% 
  ggplot() +
  geom_contour_filled(aes(x = x, y = y, z = z)) + 
  coord_fixed()

gam_humber_viz_raster$data$fit %>% 
  ggplot() +
  geom_tile(aes(x = x, y = y, fill = z)) +
  scale_fill_viridis_c() +
  coord_fixed()

# according to page 359 of GAM in R book

gam(cases ~ s(x, y,bs = "gp",k = 100), 
    data = humber_df, 
    family = binomial(link = logit)) %>% 
  getViz() %>% 
  plot(sm(., 1)) + 
  l_fitRaster() +
  l_fitContour() + 
  coord_fixed()

# gam(cases ~ s(x, y,bs = "sos",k = 100), 
#     data = humber_df, 
#     family = binomial(link = logit)) %>% 
#   getViz() %>% 
#   plot(sm(., 1)) + 
#   l_fitRaster() +
#   l_fitContour()

```

```{r}

# test assumptions --------------------------------------------------------

from_augment <- augment(gam_humber,
                        type.residuals="deviance",
                        type.predict="response")
gb<-list(data=from_augment %>% pull(.resid),
         coords=from_augment %>% select(x,y) %>% as.matrix())
# FIRST:
# variaogram of deviance residuals
# spatial autocorrelation
# uncorrelated residuals should give a more or less flat variogram
library(geoR)
plot(variog(gb,max.dist=100)) 
# SECOND:
# deviance residuals against fitted probabilities
# normal distribution or residuals
# plot(fitted(m10),residuals(m10)) #ggplot replica
from_augment %>% 
  ggplot(aes(x = .fitted,y = .resid)) +
  geom_point() +
  geom_smooth()

```

